version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/share/nginx:cached
      - ./config/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
    healthcheck:
      test: curl nginx || exit 1
      interval: 30s
      timeout: 10s

  nginx:
    image: nginx:1.15
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/public:ro
    ports:
      - 3003:80
    depends_on:
      - web

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - nginx_exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana-ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus-server:prometheus

  nginx_exporter:
    image: fish/nginx-exporter
    links:
     - nginx
    command:
      - 'nginx.scrape_uri=http:/app_prohmeteus_nginx_1/nginx_status'

